version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db_data:/usr/src/django/data
      - ./:/usr/src/django
    ports:
      - 9000:9000

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - REACT_APP_DEBUG=TRUE
    volumes:
      - ./frontend:/usr/src/react
      - /usr/src/react/node_modules
    ports:
      - 3000:3000

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest

volumes:
    db_data:
